#####################
# PARTICLE SETTINGS #
#####################

particle:
    smoke-enabled: true
    
#############################
# ARMOR PROTECTION SETTINGS #
#############################

#This is modifiers for armor protection when shot in the area of each armorpice location
#set protection enchant is static and the protection enchant modifier is dynamic depending on total default armor
#durability protection decrease rate works like this total armor - ((total armor * 100) * ((1 - durability / maxdurability) * durability protection rate)) / 100
armor:
    protection:
        durability-protection-decrease-rate: 0.6
        dynamic-protection-enchantment: 0.05
        static-protection-enchantment: 0.07
        helmet:
            leather: 0.15
            gold: 0.17
            chain: 0.2
            iron: 0.34
            diamond: 0.64
        chestplate:
            leather: 0.17
            gold: 0.2
            chain: 0.32
            iron: 0.41
            diamond: 0.73
        leggings:
            leather: 0.16
            gold: 0.19
            chain: 0.28
            iron: 0.37
            diamond: 0.68

#######################
# PROJECTILE SETTINGS #
#######################

projectile:
    ignored-blocks:
        - "GRASS"
        - "TALL_GRASS"
        - "VINE"
        - "STRING"
        - "COBWEB"
    ignore-open:
        fence-gate: true
    speed-reduction:
        entity: 0.3
        obsticle: 0.03
    penetration-reduction: 
        obsticle: 0.02
        armor: 0.4
        entity: 0.2
    damage-reduction:
        speed: 0.7
        penetration: 0.5

###################
# DAMAGE SETTINGS #
###################

damage:
    break-leg:
        enabled: true
        height: 4
        chance-per-legdamage: 0.06
        time-active-ticks:  24000
    concussion:
        enabled: true
        chance-hit-head: 0.1
        chance-per-headdamage: 0.08
        time-active-ticks:  12000
    bleeding:
        enabled: true
        chance-per-damage: 0.04
        bleeding-per-damage: 0.1
        time-active-ticks:  6000

###################
# WEAPON SHOOTING #
###################

shooting:
    recoil:
        enabled: true
        yaw-modifier: 0.2
    knockback:
        enabled true